### ISSUE TITLE
Cannot use AI Runner

### ISSUE THREAD

**Issue by CHJ85** [w4ffl35/krita_stable_diffusion#114]
Hi there. I'm getting all kinds of different error messages.
```
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 374, in __init__
OSError: /home/chris/ai-runner/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "torch/__init__.py", line 217, in <module>
  File "torch/__init__.py", line 177, in _load_global_deps
  File "torch/__init__.py", line 172, in _load_global_deps
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '/home/chris/ai-runner/torch/lib/libtorch_global_deps.so'. Most likely this dynlib/dll was not found when the application was frozen.
[3777358] Failed to execute script 'main' due to unhandled exception!

```
I couldn't find contact info on your site, so I decided to post it here instead.

**Comment by w4ffl35** [comment]
Hi @CHJ85 
I'm guessing your issue is resolved as this is a week old post, but I can help you out if you're still having issues with the latest version.

Please move discussion to [discord](https://discord.gg/8nHFCMb35R)  or the [AI Runner community forum](https://capsizegames.itch.io/ai-runner/community).
